/** Camerafy - Copy right. All rights reserved. */
/** AUTOGENERATED CODE. DO NOT TOUCH. */
/** 1/06/2020 9:50:39 AM */
/* eslint-disable */

function EncodeString(str : string, buffer : ArrayBuffer, index : number, writeSize = true) : number
{
	if(!writeSize)
		return (new TextEncoder('UTF-8').encodeInto(str, new Uint8Array(buffer, index))).written;

	const result = new TextEncoder('UTF-8').encodeInto(str, new Uint8Array(buffer, index + 4));
	const tmp = new DataView(buffer, index);
	tmp.setUint32(0, result.written, true);
	return result.written + 4;
}

function DecodeString(InUint8Arr : Uint8Array, index : number, length : number) : string
{
	return new TextDecoder('UTF-8').decode(new Uint8Array(InUint8Arr.buffer, index, length));
}

function GetArrayOfStringByteCount(InStringArray)
{
	let Count = 0;
	let n;
	for(n = 0; n < InStringArray.length; n++)
	{
		Count += InStringArray[n].length;
	}
	return Count;
}


export default class Camerafy
{
	private PendingRequests : Map<string, any>;
	private UUIDGenerator : { () : void };

	constructor()
	{
		this.PendingRequests = new Map<string, any>();
	}

	initialize(uuidGenerator : { () : void })
	{
		this.UUIDGenerator = uuidGenerator;
	}


	private onSessionDataRecv(InUint8Arr : Uint8Array) : void
	{
			let name = DecodeString(InUint8Arr, 0, 32);

			if(name == "00000000000000000000000000000000")
			{
				let data = new DataView(InUint8Arr.buffer);
				let offset = 32;
				let len = 0;
				len = data.getInt32(offset, true); offset += 4;
				const MessageId = DecodeString(InUint8Arr, offset, len); offset += len;
				len = data.getInt32(offset, true); offset += 4;
				const ReturnJson = DecodeString(InUint8Arr, offset, len);
				this.onMessageResponse(MessageId, ReturnJson);
				return;
			}

			let args = eval(`__${name}`)(InUint8Arr);
			this.EventBus.$emit.apply(this.EventBus, [name].concat(args));

			/* Server side events argument parser */
			function __7a98bb606d933cc05bafb4812fc95c0f(InUint8Arr : Uint8Array)
			{
				let Args = new Array<any>();
				return Args;
			}
			
			function __665f90d8fc016dab152813b79f6ccf37(InUint8Arr : Uint8Array)
			{
				let Args = new Array<any>();
				return Args;
			}
			
			function __54efa4d8a26ac28fcb8fd6e1b0ae5128(InUint8Arr : Uint8Array)
			{
				let Args = new Array<any>();
				let data = new DataView(InUint8Arr.buffer);
				let offset = 32; // skip first bytes, as they hold the method address
				let n = 0;
				let N = 1;
				let len = 0;
			
				/* sdp */
				let arg0 = [];
				len = data.getInt32(offset, true); offset += 4;
				arg0 = DecodeString(InUint8Arr, offset, len); offset += len;
				Args.push(arg0);
			
				return Args;
			}
			
			function __c914ec502d666eba9669f88b293e61b7(InUint8Arr : Uint8Array)
			{
				let Args = new Array<any>();
				let data = new DataView(InUint8Arr.buffer);
				let offset = 32; // skip first bytes, as they hold the method address
				let n = 0;
				let N = 1;
				let len = 0;
			
				/* SnapshotId */
				let arg0 = [];
				arg0 = data.getInt32(offset, true); offset += 4;
				Args.push(arg0);
			
				return Args;
			}
			
			function __f2cefd1ff00b4267ff15df2a7fde054d(InUint8Arr : Uint8Array)
			{
				let Args = new Array<any>();
				let data = new DataView(InUint8Arr.buffer);
				let offset = 32; // skip first bytes, as they hold the method address
				let n = 0;
				let N = 1;
				let len = 0;
			
				/* JsonCameraData */
				let arg0 = [];
				len = data.getInt32(offset, true); offset += 4;
				arg0 = DecodeString(InUint8Arr, offset, len); offset += len;
				Args.push(arg0);
			
				return Args;
			}
			
			function __ade994924a143e2cdaa99c94d7237b59(InUint8Arr : Uint8Array)
			{
				let Args = new Array<any>();
				return Args;
			}
			
			function __f3bb377fea4c2b0036490e3484bacc6c(InUint8Arr : Uint8Array)
			{
				let Args = new Array<any>();
				let data = new DataView(InUint8Arr.buffer);
				let offset = 32; // skip first bytes, as they hold the method address
				let n = 0;
				let N = 1;
				let len = 0;
			
				/* NewEnvirionment */
				let arg0 = [];
				len = data.getInt32(offset, true); offset += 4;
				arg0 = DecodeString(InUint8Arr, offset, len); offset += len;
				Args.push(arg0);
			
				return Args;
			}
			
	}

		private onMessageResponse(InMessageId : string, InReturnJson : string) : void
		{
			const PromiseResolve = this.PendingRequests.get(InMessageId);
			if(PromiseResolve === undefined)
			{
				console.error("Received response for unknown request.");
				return;
			}
			this.PendingRequests.delete(InMessageId);
			PromiseResolve(JSON.parse(InReturnJson));
		}

	get User()
	{
		return {
			User:
			{
				ClientRtcReady: () =>
				{
					let OpCode = new ArrayBuffer(64);
					let data = new DataView(OpCode);
					let offset = 0;
					let n = 0;
					let N = 1;
					let len = 0;
					const messageId = UUIDGenerator();
				
					offset += EncodeString(messageId, OpCode, offset, false);
					offset += EncodeString("734a882f52a3c4a50b78e34ec986e14a", OpCode, offset, false);
				
				
					return OpCode;
				},

				NewIceCandidateReady: (candidate : string, sdp_mlineindex : number, sdp_mid : string) =>
				{
					let OpCode = new ArrayBuffer(64 + (4 + candidate.length) + 4 + (4 + sdp_mid.length));
					let data = new DataView(OpCode);
					let offset = 0;
					let n = 0;
					let N = 1;
					let len = 0;
					const messageId = UUIDGenerator();
				
					offset += EncodeString(messageId, OpCode, offset, false);
					offset += EncodeString("fcf565226f73bf227bb40d768746f5af", OpCode, offset, false);
				
					/* candidate */
					offset += EncodeString(candidate, OpCode, offset);
				
					/* sdp_mlineindex */
					data.setInt32(offset, sdp_mlineindex, true); offset += 4;
				
					/* sdp_mid */
					offset += EncodeString(sdp_mid, OpCode, offset);
				
				
					return OpCode;
				},

				ClientRtcAnswer: (sdp : string) =>
				{
					let OpCode = new ArrayBuffer(64 + (4 + sdp.length));
					let data = new DataView(OpCode);
					let offset = 0;
					let n = 0;
					let N = 1;
					let len = 0;
					const messageId = UUIDGenerator();
				
					offset += EncodeString(messageId, OpCode, offset, false);
					offset += EncodeString("dca947e0cfef33fe4c01d9d333901318", OpCode, offset, false);
				
					/* sdp */
					offset += EncodeString(sdp, OpCode, offset);
				
				
					return OpCode;
				},

				Disconnect: () =>
				{
					let OpCode = new ArrayBuffer(64);
					let data = new DataView(OpCode);
					let offset = 0;
					let n = 0;
					let N = 1;
					let len = 0;
					const messageId = UUIDGenerator();
				
					offset += EncodeString(messageId, OpCode, offset, false);
					offset += EncodeString("154c06d97f7bcc2e3511b67d9534f463", OpCode, offset, false);
				
				
					return OpCode;
				},

				RequestCameraSnapshot: (width : number, height : number, format : string) =>
				{
					let OpCode = new ArrayBuffer(64 + 4 + 4 + (4 + format.length));
					let data = new DataView(OpCode);
					let offset = 0;
					let n = 0;
					let N = 1;
					let len = 0;
					const messageId = UUIDGenerator();
				
					offset += EncodeString(messageId, OpCode, offset, false);
					offset += EncodeString("5527f595e783a6d3ed2b9102a274d64a", OpCode, offset, false);
				
					/* width */
					data.setInt32(offset, width, true); offset += 4;
				
					/* height */
					data.setInt32(offset, height, true); offset += 4;
				
					/* format */
					offset += EncodeString(format, OpCode, offset);
				
				
					return OpCode;
				},

				GetEnvironmentInfo: () =>
				{
					let OpCode = new ArrayBuffer(64);
					let data = new DataView(OpCode);
					let offset = 0;
					let n = 0;
					let N = 1;
					let len = 0;
					const messageId = UUIDGenerator();
				
					offset += EncodeString(messageId, OpCode, offset, false);
					offset += EncodeString("63ccf80e1f16e0b8bfe676e738965fb8", OpCode, offset, false);
				
				
					return OpCode;
				},

			},

		}
	}

	get Input()
	{
		return {
			RemoteInputModule:
			{
				ProcessRemoteKeyboardInput: (IsKeyDown : boolean, IsRepeat : boolean, KeyCode : any, Char : string) =>
				{
					let OpCode = new ArrayBuffer(64 + 1 + 1 + 1 + 2);
					let data = new DataView(OpCode);
					let offset = 0;
					let n = 0;
					let N = 1;
					let len = 0;
					const messageId = UUIDGenerator();
				
					offset += EncodeString(messageId, OpCode, offset, false);
					offset += EncodeString("9fd75e9e59f69c333db196a69e511da7", OpCode, offset, false);
				
					/* IsKeyDown */
					data.setInt8(offset, IsKeyDown); offset += 1;
				
					/* IsRepeat */
					data.setInt8(offset, IsRepeat); offset += 1;
				
					/* KeyCode */
					data.setInt8(offset, KeyCode); offset += 1;
				
					/* Char */
					data.setInt16(offset, Char, true); offset += 2;
				
				
					return OpCode;
				},

				ProcessRemoteMouseInput: (Xpos : number, Ypos : number, Button : any) =>
				{
					let OpCode = new ArrayBuffer(64 + 2 + 2 + 1);
					let data = new DataView(OpCode);
					let offset = 0;
					let n = 0;
					let N = 1;
					let len = 0;
					const messageId = UUIDGenerator();
				
					offset += EncodeString(messageId, OpCode, offset, false);
					offset += EncodeString("4852d5f18ccf0539751d6e89db91c2da", OpCode, offset, false);
				
					/* Xpos */
					data.setInt16(offset, Xpos, true); offset += 2;
				
					/* Ypos */
					data.setInt16(offset, Ypos, true); offset += 2;
				
					/* Button */
					data.setInt8(offset, Button); offset += 1;
				
				
					return OpCode;
				},

				ProcessRemoteMouseWheelInput: (ScrollX : number, ScrollY : number) =>
				{
					let OpCode = new ArrayBuffer(64 + 4 + 4);
					let data = new DataView(OpCode);
					let offset = 0;
					let n = 0;
					let N = 1;
					let len = 0;
					const messageId = UUIDGenerator();
				
					offset += EncodeString(messageId, OpCode, offset, false);
					offset += EncodeString("1cd4fb4231b1314ce46fed8c8fa89c38", OpCode, offset, false);
				
					/* ScrollX */
					data.setFloat32(offset, ScrollX, true); offset += 4;
				
					/* ScrollY */
					data.setFloat32(offset, ScrollY, true); offset += 4;
				
				
					return OpCode;
				},

				ProcessRemoteTouchInput: (NumTouches : number, TouchId : Array<any>, Phase : Array<any>, XPos : Array<any>, YPos : Array<any>, Force : Array<any>) =>
				{
					let OpCode = new ArrayBuffer(64 + 4 + 	(4 + (TouchId.length * 4)) + 	(4 + Phase.length) + 	(4 + (XPos.length * 2)) + 	(4 + (YPos.length * 2)) + 	(4 + (Force.length * 4)));
					let data = new DataView(OpCode);
					let offset = 0;
					let n = 0;
					let N = 1;
					let len = 0;
					const messageId = UUIDGenerator();
				
					offset += EncodeString(messageId, OpCode, offset, false);
					offset += EncodeString("81c54a832bc54c96e3801a4988390fe6", OpCode, offset, false);
				
					/* NumTouches */
					data.setInt32(offset, NumTouches, true); offset += 4;
				
					/* TouchId */
					N = TouchId.length; data.setUint32(offset, N, true); offset += 4;
					for(n = 0; n < N; n++)
					{
						data.setInt32(offset, TouchId[n], true); offset += 4;
					}
				
					/* Phase */
					N = Phase.length; data.setUint32(offset, N, true); offset += 4;
					for(n = 0; n < N; n++)
					{
						data.setInt8(offset, Phase[n]); offset += 1;
					}
				
					/* XPos */
					N = XPos.length; data.setUint32(offset, N, true); offset += 4;
					for(n = 0; n < N; n++)
					{
						data.setInt16(offset, XPos[n], true); offset += 2;
					}
				
					/* YPos */
					N = YPos.length; data.setUint32(offset, N, true); offset += 4;
					for(n = 0; n < N; n++)
					{
						data.setInt16(offset, YPos[n], true); offset += 2;
					}
				
					/* Force */
					N = Force.length; data.setUint32(offset, N, true); offset += 4;
					for(n = 0; n < N; n++)
					{
						data.setFloat32(offset, Force[n], true); offset += 4;
					}
				
				
					return OpCode;
				},

			},

		}
	}

	get Camera()
	{
		return {
			CameraController:
			{
				SetMaxLinearSpeed: (InMaxLinearSpeed : number) =>
				{
					let OpCode = new ArrayBuffer(64 + 4);
					let data = new DataView(OpCode);
					let offset = 0;
					let n = 0;
					let N = 1;
					let len = 0;
					const messageId = UUIDGenerator();
				
					offset += EncodeString(messageId, OpCode, offset, false);
					offset += EncodeString("026557a832401d261de1976574ede7b8", OpCode, offset, false);
				
					/* InMaxLinearSpeed */
					data.setFloat32(offset, InMaxLinearSpeed, true); offset += 4;
				
				
					return OpCode;
				},

				SetMaxAngularSpeed: (InMaxAngularSpeed : number) =>
				{
					let OpCode = new ArrayBuffer(64 + 4);
					let data = new DataView(OpCode);
					let offset = 0;
					let n = 0;
					let N = 1;
					let len = 0;
					const messageId = UUIDGenerator();
				
					offset += EncodeString(messageId, OpCode, offset, false);
					offset += EncodeString("5b815722e2abd45ecb150985ac3d2c71", OpCode, offset, false);
				
					/* InMaxAngularSpeed */
					data.setFloat32(offset, InMaxAngularSpeed, true); offset += 4;
				
				
					return OpCode;
				},

				SetInvertControls: (InState : boolean) =>
				{
					let OpCode = new ArrayBuffer(64 + 1);
					let data = new DataView(OpCode);
					let offset = 0;
					let n = 0;
					let N = 1;
					let len = 0;
					const messageId = UUIDGenerator();
				
					offset += EncodeString(messageId, OpCode, offset, false);
					offset += EncodeString("9e91fb0bcab699c09a0fb38559f940ef", OpCode, offset, false);
				
					/* InState */
					data.setInt8(offset, InState); offset += 1;
				
				
					return OpCode;
				},

				SetLinearDamping: (InDamping : number) =>
				{
					let OpCode = new ArrayBuffer(64 + 4);
					let data = new DataView(OpCode);
					let offset = 0;
					let n = 0;
					let N = 1;
					let len = 0;
					const messageId = UUIDGenerator();
				
					offset += EncodeString(messageId, OpCode, offset, false);
					offset += EncodeString("04e6e0b3e93be80c10852866d545edd4", OpCode, offset, false);
				
					/* InDamping */
					data.setFloat32(offset, InDamping, true); offset += 4;
				
				
					return OpCode;
				},

				SetAngularDamping: (InDamping : number) =>
				{
					let OpCode = new ArrayBuffer(64 + 4);
					let data = new DataView(OpCode);
					let offset = 0;
					let n = 0;
					let N = 1;
					let len = 0;
					const messageId = UUIDGenerator();
				
					offset += EncodeString(messageId, OpCode, offset, false);
					offset += EncodeString("ae310fa100ec938961ae9e9cfff40507", OpCode, offset, false);
				
					/* InDamping */
					data.setFloat32(offset, InDamping, true); offset += 4;
				
				
					return OpCode;
				},

				SetCameraTarget: (InX : number, InY : number, InZ : number) =>
				{
					let OpCode = new ArrayBuffer(64 + 4 + 4 + 4);
					let data = new DataView(OpCode);
					let offset = 0;
					let n = 0;
					let N = 1;
					let len = 0;
					const messageId = UUIDGenerator();
				
					offset += EncodeString(messageId, OpCode, offset, false);
					offset += EncodeString("6b8a57c4876b8f590d0af2f369508b19", OpCode, offset, false);
				
					/* InX */
					data.setFloat32(offset, InX, true); offset += 4;
				
					/* InY */
					data.setFloat32(offset, InY, true); offset += 4;
				
					/* InZ */
					data.setFloat32(offset, InZ, true); offset += 4;
				
				
					return OpCode;
				},

				SetCameraTargetByName: (InTargetName : string) =>
				{
					let OpCode = new ArrayBuffer(64 + (4 + InTargetName.length));
					let data = new DataView(OpCode);
					let offset = 0;
					let n = 0;
					let N = 1;
					let len = 0;
					const messageId = UUIDGenerator();
				
					offset += EncodeString(messageId, OpCode, offset, false);
					offset += EncodeString("cb818532b951838613febc492731319a", OpCode, offset, false);
				
					/* InTargetName */
					offset += EncodeString(InTargetName, OpCode, offset);
				
				
					return OpCode;
				},

				SetFreeBehaviour: (Weight : number) =>
				{
					let OpCode = new ArrayBuffer(64 + 4);
					let data = new DataView(OpCode);
					let offset = 0;
					let n = 0;
					let N = 1;
					let len = 0;
					const messageId = UUIDGenerator();
				
					offset += EncodeString(messageId, OpCode, offset, false);
					offset += EncodeString("65ab0ede9d770a07f696887365ea8d3f", OpCode, offset, false);
				
					/* Weight */
					data.setFloat32(offset, Weight, true); offset += 4;
				
				
					return OpCode;
				},

				SetOrbitBehaviour: (Weight : number) =>
				{
					let OpCode = new ArrayBuffer(64 + 4);
					let data = new DataView(OpCode);
					let offset = 0;
					let n = 0;
					let N = 1;
					let len = 0;
					const messageId = UUIDGenerator();
				
					offset += EncodeString(messageId, OpCode, offset, false);
					offset += EncodeString("109f8afb1a192f46a42139c3b22c7666", OpCode, offset, false);
				
					/* Weight */
					data.setFloat32(offset, Weight, true); offset += 4;
				
				
					return OpCode;
				},

			},

		}
	}

	get Application()
	{
		return {
			Session:
			{
				Connect: (InUserId : string) =>
				{
					let OpCode = new ArrayBuffer(64 + (4 + InUserId.length));
					let data = new DataView(OpCode);
					let offset = 0;
					let n = 0;
					let N = 1;
					let len = 0;
					const messageId = UUIDGenerator();
				
					offset += EncodeString(messageId, OpCode, offset, false);
					offset += EncodeString("c2304902e2fc705875403e341ee86306", OpCode, offset, false);
				
					/* InUserId */
					offset += EncodeString(InUserId, OpCode, offset);
				
				
					return OpCode;
				},

				ChangeEnvironment: (InEnvironmentDescJson : string) =>
				{
					let OpCode = new ArrayBuffer(64 + (4 + InEnvironmentDescJson.length));
					let data = new DataView(OpCode);
					let offset = 0;
					let n = 0;
					let N = 1;
					let len = 0;
					const messageId = UUIDGenerator();
				
					offset += EncodeString(messageId, OpCode, offset, false);
					offset += EncodeString("4a4e6dda9dd3282ac568f8bd0dba4964", OpCode, offset, false);
				
					/* InEnvironmentDescJson */
					offset += EncodeString(InEnvironmentDescJson, OpCode, offset);
				
				
					return OpCode;
				},

				ChangeEnvironmentSocket: (InSocketName : string, InModelJsonDesc : string) =>
				{
					let OpCode = new ArrayBuffer(64 + (4 + InSocketName.length) + (4 + InModelJsonDesc.length));
					let data = new DataView(OpCode);
					let offset = 0;
					let n = 0;
					let N = 1;
					let len = 0;
					const messageId = UUIDGenerator();
				
					offset += EncodeString(messageId, OpCode, offset, false);
					offset += EncodeString("0d60d46d9a6eaf3ab7071e428bd6f2d6", OpCode, offset, false);
				
					/* InSocketName */
					offset += EncodeString(InSocketName, OpCode, offset);
				
					/* InModelJsonDesc */
					offset += EncodeString(InModelJsonDesc, OpCode, offset);
				
				
					return OpCode;
				},

				GetEnvironmentSockets: () =>
				{
					let OpCode = new ArrayBuffer(64);
					let data = new DataView(OpCode);
					let offset = 0;
					let n = 0;
					let N = 1;
					let len = 0;
					const messageId = UUIDGenerator();
				
					offset += EncodeString(messageId, OpCode, offset, false);
					offset += EncodeString("97146f433ae588ccd631d240c0dce3ec", OpCode, offset, false);
				
				
					return OpCode;
				},

			},

		}
	}

};

/* Server side events */
export const TimeoutServerEvent = "7a98bb606d933cc05bafb4812fc95c0f";
export const ServerRtcClientReadyServerEvent = "665f90d8fc016dab152813b79f6ccf37";
export const ServerRtcOfferServerEvent = "54efa4d8a26ac28fcb8fd6e1b0ae5128";
export const NewSnapshotAvailableServerEvent = "c914ec502d666eba9669f88b293e61b7";
export const InitialCameraValuesServerEvent = "f2cefd1ff00b4267ff15df2a7fde054d";
export const SessionTerminateServerEvent = "ade994924a143e2cdaa99c94d7237b59";
export const EnvironmentChangedServerEvent = "f3bb377fea4c2b0036490e3484bacc6c";

