# Generated by Django 2.2.6 on 2020-01-18 18:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('i18n', '0001_initial'), ('i18n', '0002_translationkey_type')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lan_code', models.CharField(max_length=8, unique=True)),
                ('lan_name', models.CharField(max_length=128)),
                ('reg_code', models.CharField(max_length=4)),
                ('reg_name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'i18n_languages',
            },
        ),
        migrations.CreateModel(
            name='TranslationKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=256, unique=True, validators=[django.core.validators.RegexValidator(message='Translation key may only contain alpha-numeric letters, underscore or periode sings.', regex='^[a-zA-Z0-9._]*(?<![_.])$')])),
                ('type', models.CharField(choices=[('S', 'string'), ('B', 'bool')], default='S', max_length=1)),
            ],
            options={
                'db_table': 'i18n_translation_keys',
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.TextField()),
                ('revision', models.BigIntegerField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='i18n.Language')),
                ('translation_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='i18n.TranslationKey')),
            ],
            options={
                'db_table': 'i18n_translations',
            },
        ),
    ]
