# Generated by Django 2.2.6 on 2019-12-14 08:53

import backend.api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CamerafySnapshotThumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('format', models.CharField(choices=[('PNG', 'PNG'), ('TGA', 'TGA'), ('JPG', 'JPG'), ('EXR', 'EXR'), ('RAW', 'RAW')], max_length=3)),
                ('width', models.PositiveSmallIntegerField()),
                ('height', models.PositiveSmallIntegerField()),
                ('size', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to=backend.api.models.snapshots.snapshots_storage)),
            ],
            options={
                'db_table': 'camfy_snapshot_thumbnail',
            },
        ),
        migrations.CreateModel(
            name='CamerafySnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=256, unique=True)),
                ('description', models.TextField(max_length=1024)),
                ('format', models.CharField(choices=[('PNG', 'PNG'), ('TGA', 'TGA'), ('JPG', 'JPG'), ('EXR', 'EXR'), ('RAW', 'RAW')], max_length=3)),
                ('width', models.PositiveSmallIntegerField()),
                ('height', models.PositiveSmallIntegerField()),
                ('size', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to=backend.api.models.snapshots.snapshots_storage)),
                ('seen', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thumbnail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CamerafySnapshotThumbnail')),
            ],
            options={
                'db_table': 'camfy_snapshot',
            },
        ),
    ]
