# Generated by Django 3.0.2 on 2020-02-02 11:30

import backend.api.models.environments
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191228_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentThumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('PNG', 'PNG'), ('TGA', 'TGA'), ('JPG', 'JPG'), ('EXR', 'EXR'), ('RAW', 'RAW')], max_length=3)),
                ('width', models.PositiveSmallIntegerField()),
                ('height', models.PositiveSmallIntegerField()),
                ('size', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to=backend.api.models.environments.thumbnail_storage)),
            ],
            options={
                'db_table': 'camfy_environment_thumbs',
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('brief', models.CharField(max_length=512, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('desc_json', models.TextField()),
                ('thumbnail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.EnvironmentThumbnail')),
            ],
            options={
                'db_table': 'camfy_environments',
            },
        ),
    ]
