# Generated by Django 3.0.2 on 2020-02-02 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_env_and_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.EnvironmentThumbnail'),
        ),
    ]
