# Generated by Django 3.0.2 on 2020-03-07 12:54

import backend.api.models.camfymodels
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200215_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='CamfyModelThumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('PNG', 'PNG'), ('TGA', 'TGA'), ('JPG', 'JPG'), ('EXR', 'EXR'), ('RAW', 'RAW')], max_length=3)),
                ('width', models.PositiveSmallIntegerField()),
                ('height', models.PositiveSmallIntegerField()),
                ('size', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to=backend.api.models.camfymodels.thumbnail_storage)),
            ],
            options={
                'db_table': 'camfy_model_thumbs',
            },
        ),
        migrations.CreateModel(
            name='CamfyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('brief', models.CharField(max_length=512)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('desc_json', models.TextField()),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.CamfyModelThumbnail')),
            ],
            options={
                'db_table': 'camfy_models',
            },
        ),
    ]
