# Generated by Django 3.0.2 on 2020-03-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_models_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Touchpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('brief', models.CharField(max_length=512)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('desc_json', models.TextField()),
            ],
            options={
                'db_table': 'camfy_touchpoints',
            },
        ),
    ]
